<?php

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->truncate();
        
$city = array(
  array('id' => '1','province_id' => '1','name' => 'تبريز'),
  array('id' => '2','province_id' => '1','name' => 'كندوان'),
  array('id' => '3','province_id' => '1','name' => 'بندر شرفخانه'),
  array('id' => '4','province_id' => '1','name' => 'مراغه'),
  array('id' => '5','province_id' => '1','name' => 'ميانه'),
  array('id' => '6','province_id' => '1','name' => 'شبستر'),
  array('id' => '7','province_id' => '1','name' => 'مرند'),
  array('id' => '8','province_id' => '1','name' => 'جلفا'),
  array('id' => '9','province_id' => '1','name' => 'سراب'),
  array('id' => '10','province_id' => '1','name' => 'هاديشهر'),
  array('id' => '11','province_id' => '1','name' => 'بناب'),
  array('id' => '12','province_id' => '1','name' => 'كليبر'),
  array('id' => '13','province_id' => '1','name' => 'تسوج'),
  array('id' => '14','province_id' => '1','name' => 'اهر'),
  array('id' => '15','province_id' => '1','name' => 'هريس'),
  array('id' => '16','province_id' => '1','name' => 'عجبشير'),
  array('id' => '17','province_id' => '1','name' => 'هشترود'),
  array('id' => '18','province_id' => '1','name' => 'ملكان'),
  array('id' => '19','province_id' => '1','name' => 'بستان آباد'),
  array('id' => '20','province_id' => '1','name' => 'ورزقان'),
  array('id' => '21','province_id' => '1','name' => 'اسكو'),
  array('id' => '22','province_id' => '1','name' => 'آذر شهر'),
  array('id' => '23','province_id' => '1','name' => 'قره آغاج'),
  array('id' => '24','province_id' => '1','name' => 'ممقان'),
  array('id' => '25','province_id' => '1','name' => 'صوفیان'),
  array('id' => '26','province_id' => '1','name' => 'ایلخچی'),
  array('id' => '27','province_id' => '1','name' => 'خسروشهر'),
  array('id' => '28','province_id' => '1','name' => 'باسمنج'),
  array('id' => '29','province_id' => '1','name' => 'سهند'),
  array('id' => '30','province_id' => '2','name' => 'اروميه'),
  array('id' => '31','province_id' => '2','name' => 'نقده'),
  array('id' => '32','province_id' => '2','name' => 'ماكو'),
  array('id' => '33','province_id' => '2','name' => 'تكاب'),
  array('id' => '34','province_id' => '2','name' => 'خوي'),
  array('id' => '35','province_id' => '2','name' => 'مهاباد'),
  array('id' => '36','province_id' => '2','name' => 'سر دشت'),
  array('id' => '37','province_id' => '2','name' => 'چالدران'),
  array('id' => '38','province_id' => '2','name' => 'بوكان'),
  array('id' => '39','province_id' => '2','name' => 'مياندوآب'),
  array('id' => '40','province_id' => '2','name' => 'سلماس'),
  array('id' => '41','province_id' => '2','name' => 'شاهين دژ'),
  array('id' => '42','province_id' => '2','name' => 'پيرانشهر'),
  array('id' => '43','province_id' => '2','name' => 'سيه چشمه'),
  array('id' => '44','province_id' => '2','name' => 'اشنويه'),
  array('id' => '45','province_id' => '2','name' => 'چایپاره'),
  array('id' => '46','province_id' => '2','name' => 'پلدشت'),
  array('id' => '47','province_id' => '2','name' => 'شوط'),
  array('id' => '48','province_id' => '3','name' => 'اردبيل'),
  array('id' => '49','province_id' => '3','name' => 'سرعين'),
  array('id' => '50','province_id' => '3','name' => 'بيله سوار'),
  array('id' => '51','province_id' => '3','name' => 'پارس آباد'),
  array('id' => '52','province_id' => '3','name' => 'خلخال'),
  array('id' => '53','province_id' => '3','name' => 'مشگين شهر'),
  array('id' => '54','province_id' => '3','name' => 'مغان'),
  array('id' => '55','province_id' => '3','name' => 'نمين'),
  array('id' => '56','province_id' => '3','name' => 'نير'),
  array('id' => '57','province_id' => '3','name' => 'كوثر'),
  array('id' => '58','province_id' => '3','name' => 'كيوي'),
  array('id' => '59','province_id' => '3','name' => 'گرمي'),
  array('id' => '60','province_id' => '4','name' => 'اصفهان'),
  array('id' => '61','province_id' => '4','name' => 'فريدن'),
  array('id' => '62','province_id' => '4','name' => 'فريدون شهر'),
  array('id' => '63','province_id' => '4','name' => 'فلاورجان'),
  array('id' => '64','province_id' => '4','name' => 'گلپايگان'),
  array('id' => '65','province_id' => '4','name' => 'دهاقان'),
  array('id' => '66','province_id' => '4','name' => 'نطنز'),
  array('id' => '67','province_id' => '4','name' => 'نايين'),
  array('id' => '68','province_id' => '4','name' => 'تيران'),
  array('id' => '69','province_id' => '4','name' => 'كاشان'),
  array('id' => '70','province_id' => '4','name' => 'فولاد شهر'),
  array('id' => '71','province_id' => '4','name' => 'اردستان'),
  array('id' => '72','province_id' => '4','name' => 'سميرم'),
  array('id' => '73','province_id' => '4','name' => 'درچه'),
  array('id' => '74','province_id' => '4','name' => 'کوهپایه'),
  array('id' => '75','province_id' => '4','name' => 'مباركه'),
  array('id' => '76','province_id' => '4','name' => 'شهرضا'),
  array('id' => '77','province_id' => '4','name' => 'خميني شهر'),
  array('id' => '78','province_id' => '4','name' => 'شاهين شهر'),
  array('id' => '79','province_id' => '4','name' => 'نجف آباد'),
  array('id' => '80','province_id' => '4','name' => 'دولت آباد'),
  array('id' => '81','province_id' => '4','name' => 'زرين شهر'),
  array('id' => '82','province_id' => '4','name' => 'آران و بيدگل'),
  array('id' => '83','province_id' => '4','name' => 'باغ بهادران'),
  array('id' => '84','province_id' => '4','name' => 'خوانسار'),
  array('id' => '85','province_id' => '4','name' => 'مهردشت'),
  array('id' => '86','province_id' => '4','name' => 'علويجه'),
  array('id' => '87','province_id' => '4','name' => 'عسگران'),
  array('id' => '88','province_id' => '4','name' => 'نهضت آباد'),
  array('id' => '89','province_id' => '4','name' => 'حاجي آباد'),
  array('id' => '90','province_id' => '4','name' => 'تودشک'),
  array('id' => '91','province_id' => '4','name' => 'ورزنه'),
  array('id' => '92','province_id' => '6','name' => 'ايلام'),
  array('id' => '93','province_id' => '6','name' => 'مهران'),
  array('id' => '94','province_id' => '6','name' => 'دهلران'),
  array('id' => '95','province_id' => '6','name' => 'آبدانان'),
  array('id' => '96','province_id' => '6','name' => 'شيروان چرداول'),
  array('id' => '97','province_id' => '6','name' => 'دره شهر'),
  array('id' => '98','province_id' => '6','name' => 'ايوان'),
  array('id' => '99','province_id' => '6','name' => 'سرابله'),
  array('id' => '100','province_id' => '7','name' => 'بوشهر'),
  array('id' => '101','province_id' => '7','name' => 'تنگستان'),
  array('id' => '102','province_id' => '7','name' => 'دشتستان'),
  array('id' => '103','province_id' => '7','name' => 'دير'),
  array('id' => '104','province_id' => '7','name' => 'ديلم'),
  array('id' => '105','province_id' => '7','name' => 'كنگان'),
  array('id' => '106','province_id' => '7','name' => 'گناوه'),
  array('id' => '107','province_id' => '7','name' => 'ريشهر'),
  array('id' => '108','province_id' => '7','name' => 'دشتي'),
  array('id' => '109','province_id' => '7','name' => 'خورموج'),
  array('id' => '110','province_id' => '7','name' => 'اهرم'),
  array('id' => '111','province_id' => '7','name' => 'برازجان'),
  array('id' => '112','province_id' => '7','name' => 'خارك'),
  array('id' => '113','province_id' => '7','name' => 'جم'),
  array('id' => '114','province_id' => '7','name' => 'کاکی'),
  array('id' => '115','province_id' => '7','name' => 'عسلویه'),
  array('id' => '116','province_id' => '7','name' => 'بردخون'),
  array('id' => '117','province_id' => '8','name' => 'تهران'),
  array('id' => '118','province_id' => '8','name' => 'ورامين'),
  array('id' => '119','province_id' => '8','name' => 'فيروزكوه'),
  array('id' => '120','province_id' => '8','name' => 'ري'),
  array('id' => '121','province_id' => '8','name' => 'دماوند'),
  array('id' => '122','province_id' => '8','name' => 'اسلامشهر'),
  array('id' => '123','province_id' => '8','name' => 'رودهن'),
  array('id' => '124','province_id' => '8','name' => 'لواسان'),
  array('id' => '125','province_id' => '8','name' => 'بومهن'),
  array('id' => '126','province_id' => '8','name' => 'تجريش'),
  array('id' => '127','province_id' => '8','name' => 'فشم'),
  array('id' => '128','province_id' => '8','name' => 'كهريزك'),
  array('id' => '129','province_id' => '8','name' => 'پاكدشت'),
  array('id' => '130','province_id' => '8','name' => 'چهاردانگه'),
  array('id' => '131','province_id' => '8','name' => 'شريف آباد'),
  array('id' => '132','province_id' => '8','name' => 'قرچك'),
  array('id' => '133','province_id' => '8','name' => 'باقرشهر'),
  array('id' => '134','province_id' => '8','name' => 'شهريار'),
  array('id' => '135','province_id' => '8','name' => 'رباط كريم'),
  array('id' => '136','province_id' => '8','name' => 'قدس'),
  array('id' => '137','province_id' => '8','name' => 'ملارد'),
  array('id' => '138','province_id' => '9','name' => 'شهركرد'),
  array('id' => '139','province_id' => '9','name' => 'فارسان'),
  array('id' => '140','province_id' => '9','name' => 'بروجن'),
  array('id' => '141','province_id' => '9','name' => 'چلگرد'),
  array('id' => '142','province_id' => '9','name' => 'اردل'),
  array('id' => '143','province_id' => '9','name' => 'لردگان'),
  array('id' => '144','province_id' => '9','name' => 'سامان'),
  array('id' => '145','province_id' => '10','name' => 'قائن'),
  array('id' => '146','province_id' => '10','name' => 'فردوس'),
  array('id' => '147','province_id' => '10','name' => 'بيرجند'),
  array('id' => '148','province_id' => '10','name' => 'نهبندان'),
  array('id' => '149','province_id' => '10','name' => 'سربيشه'),
  array('id' => '150','province_id' => '10','name' => 'طبس مسینا'),
  array('id' => '151','province_id' => '10','name' => 'قهستان'),
  array('id' => '152','province_id' => '10','name' => 'درمیان'),
  array('id' => '153','province_id' => '11','name' => 'مشهد'),
  array('id' => '154','province_id' => '11','name' => 'نيشابور'),
  array('id' => '155','province_id' => '11','name' => 'سبزوار'),
  array('id' => '156','province_id' => '11','name' => 'كاشمر'),
  array('id' => '157','province_id' => '11','name' => 'گناباد'),
  array('id' => '158','province_id' => '11','name' => 'طبس'),
  array('id' => '159','province_id' => '11','name' => 'تربت حيدريه'),
  array('id' => '160','province_id' => '11','name' => 'خواف'),
  array('id' => '161','province_id' => '11','name' => 'تربت جام'),
  array('id' => '162','province_id' => '11','name' => 'تايباد'),
  array('id' => '163','province_id' => '11','name' => 'قوچان'),
  array('id' => '164','province_id' => '11','name' => 'سرخس'),
  array('id' => '165','province_id' => '11','name' => 'بردسكن'),
  array('id' => '166','province_id' => '11','name' => 'فريمان'),
  array('id' => '167','province_id' => '11','name' => 'چناران'),
  array('id' => '168','province_id' => '11','name' => 'درگز'),
  array('id' => '169','province_id' => '11','name' => 'كلات'),
  array('id' => '170','province_id' => '11','name' => 'طرقبه'),
  array('id' => '171','province_id' => '11','name' => 'سر ولایت'),
  array('id' => '172','province_id' => '12','name' => 'بجنورد'),
  array('id' => '173','province_id' => '12','name' => 'اسفراين'),
  array('id' => '174','province_id' => '12','name' => 'جاجرم'),
  array('id' => '175','province_id' => '12','name' => 'شيروان'),
  array('id' => '176','province_id' => '12','name' => 'آشخانه'),
  array('id' => '177','province_id' => '12','name' => 'گرمه'),
  array('id' => '178','province_id' => '12','name' => 'ساروج'),
  array('id' => '179','province_id' => '13','name' => 'اهواز'),
  array('id' => '180','province_id' => '13','name' => 'ايرانشهر'),
  array('id' => '181','province_id' => '13','name' => 'شوش'),
  array('id' => '182','province_id' => '13','name' => 'آبادان'),
  array('id' => '183','province_id' => '13','name' => 'خرمشهر'),
  array('id' => '184','province_id' => '13','name' => 'مسجد سليمان'),
  array('id' => '185','province_id' => '13','name' => 'ايذه'),
  array('id' => '186','province_id' => '13','name' => 'شوشتر'),
  array('id' => '187','province_id' => '13','name' => 'انديمشك'),
  array('id' => '188','province_id' => '13','name' => 'سوسنگرد'),
  array('id' => '189','province_id' => '13','name' => 'هويزه'),
  array('id' => '190','province_id' => '13','name' => 'دزفول'),
  array('id' => '191','province_id' => '13','name' => 'شادگان'),
  array('id' => '192','province_id' => '13','name' => 'بندر ماهشهر'),
  array('id' => '193','province_id' => '13','name' => 'بندر امام خميني'),
  array('id' => '194','province_id' => '13','name' => 'اميديه'),
  array('id' => '195','province_id' => '13','name' => 'بهبهان'),
  array('id' => '196','province_id' => '13','name' => 'رامهرمز'),
  array('id' => '197','province_id' => '13','name' => 'باغ ملك'),
  array('id' => '198','province_id' => '13','name' => 'هنديجان'),
  array('id' => '199','province_id' => '13','name' => 'لالي'),
  array('id' => '200','province_id' => '13','name' => 'رامشیر'),
  array('id' => '201','province_id' => '13','name' => 'حمیدیه'),
  array('id' => '202','province_id' => '13','name' => 'دغاغله'),
  array('id' => '203','province_id' => '13','name' => 'ملاثانی'),
  array('id' => '204','province_id' => '13','name' => 'شادگان'),
  array('id' => '205','province_id' => '13','name' => 'ویسی'),
  array('id' => '206','province_id' => '14','name' => 'زنجان'),
  array('id' => '207','province_id' => '14','name' => 'ابهر'),
  array('id' => '208','province_id' => '14','name' => 'خدابنده'),
  array('id' => '209','province_id' => '14','name' => 'طارم'),
  array('id' => '210','province_id' => '14','name' => 'ماهنشان'),
  array('id' => '211','province_id' => '14','name' => 'خرمدره'),
  array('id' => '212','province_id' => '14','name' => 'ايجرود'),
  array('id' => '213','province_id' => '14','name' => 'زرين آباد'),
  array('id' => '214','province_id' => '14','name' => 'آب بر'),
  array('id' => '215','province_id' => '14','name' => 'قيدار'),
  array('id' => '216','province_id' => '15','name' => 'سمنان'),
  array('id' => '217','province_id' => '15','name' => 'شاهرود'),
  array('id' => '218','province_id' => '15','name' => 'گرمسار'),
  array('id' => '219','province_id' => '15','name' => 'ايوانكي'),
  array('id' => '220','province_id' => '15','name' => 'دامغان'),
  array('id' => '221','province_id' => '15','name' => 'بسطام'),
  array('id' => '222','province_id' => '16','name' => 'زاهدان'),
  array('id' => '223','province_id' => '16','name' => 'چابهار'),
  array('id' => '224','province_id' => '16','name' => 'خاش'),
  array('id' => '225','province_id' => '16','name' => 'سراوان'),
  array('id' => '226','province_id' => '16','name' => 'زابل'),
  array('id' => '227','province_id' => '16','name' => 'سرباز'),
  array('id' => '228','province_id' => '16','name' => 'نيكشهر'),
  array('id' => '229','province_id' => '16','name' => 'ايرانشهر'),
  array('id' => '230','province_id' => '16','name' => 'راسك'),
  array('id' => '231','province_id' => '16','name' => 'ميرجاوه'),
  array('id' => '232','province_id' => '17','name' => 'شيراز'),
  array('id' => '233','province_id' => '17','name' => 'اقليد'),
  array('id' => '234','province_id' => '17','name' => 'داراب'),
  array('id' => '235','province_id' => '17','name' => 'فسا'),
  array('id' => '236','province_id' => '17','name' => 'مرودشت'),
  array('id' => '237','province_id' => '17','name' => 'خرم بيد'),
  array('id' => '238','province_id' => '17','name' => 'آباده'),
  array('id' => '239','province_id' => '17','name' => 'كازرون'),
  array('id' => '240','province_id' => '17','name' => 'ممسني'),
  array('id' => '241','province_id' => '17','name' => 'سپيدان'),
  array('id' => '242','province_id' => '17','name' => 'لار'),
  array('id' => '243','province_id' => '17','name' => 'فيروز آباد'),
  array('id' => '244','province_id' => '17','name' => 'جهرم'),
  array('id' => '245','province_id' => '17','name' => 'ني ريز'),
  array('id' => '246','province_id' => '17','name' => 'استهبان'),
  array('id' => '247','province_id' => '17','name' => 'لامرد'),
  array('id' => '248','province_id' => '17','name' => 'مهر'),
  array('id' => '249','province_id' => '17','name' => 'حاجي آباد'),
  array('id' => '250','province_id' => '17','name' => 'نورآباد'),
  array('id' => '251','province_id' => '17','name' => 'اردكان'),
  array('id' => '252','province_id' => '17','name' => 'صفاشهر'),
  array('id' => '253','province_id' => '17','name' => 'ارسنجان'),
  array('id' => '254','province_id' => '17','name' => 'قيروكارزين'),
  array('id' => '255','province_id' => '17','name' => 'سوريان'),
  array('id' => '256','province_id' => '17','name' => 'فراشبند'),
  array('id' => '257','province_id' => '17','name' => 'سروستان'),
  array('id' => '258','province_id' => '17','name' => 'ارژن'),
  array('id' => '259','province_id' => '17','name' => 'گويم'),
  array('id' => '260','province_id' => '17','name' => 'داريون'),
  array('id' => '261','province_id' => '17','name' => 'زرقان'),
  array('id' => '262','province_id' => '17','name' => 'خان زنیان'),
  array('id' => '263','province_id' => '17','name' => 'کوار'),
  array('id' => '264','province_id' => '17','name' => 'ده بید'),
  array('id' => '265','province_id' => '17','name' => 'باب انار/خفر'),
  array('id' => '266','province_id' => '17','name' => 'بوانات'),
  array('id' => '267','province_id' => '17','name' => 'خرامه'),
  array('id' => '268','province_id' => '17','name' => 'خنج'),
  array('id' => '269','province_id' => '17','name' => 'سیاخ دارنگون'),
  array('id' => '270','province_id' => '18','name' => 'قزوين'),
  array('id' => '271','province_id' => '18','name' => 'تاكستان'),
  array('id' => '272','province_id' => '18','name' => 'آبيك'),
  array('id' => '273','province_id' => '18','name' => 'بوئين زهرا'),
  array('id' => '274','province_id' => '19','name' => 'قم'),
  array('id' => '275','province_id' => '5','name' => 'طالقان'),
  array('id' => '276','province_id' => '5','name' => 'نظرآباد'),
  array('id' => '277','province_id' => '5','name' => 'اشتهارد'),
  array('id' => '278','province_id' => '5','name' => 'هشتگرد'),
  array('id' => '279','province_id' => '5','name' => 'كن'),
  array('id' => '280','province_id' => '5','name' => 'آسارا'),
  array('id' => '281','province_id' => '5','name' => 'شهرک گلستان'),
  array('id' => '282','province_id' => '5','name' => 'اندیشه'),
  array('id' => '283','province_id' => '5','name' => 'كرج'),
  array('id' => '284','province_id' => '5','name' => 'نظر آباد'),
  array('id' => '285','province_id' => '5','name' => 'گوهردشت'),
  array('id' => '286','province_id' => '5','name' => 'ماهدشت'),
  array('id' => '287','province_id' => '5','name' => 'مشکین دشت'),
  array('id' => '288','province_id' => '20','name' => 'سنندج'),
  array('id' => '289','province_id' => '20','name' => 'ديواندره'),
  array('id' => '290','province_id' => '20','name' => 'بانه'),
  array('id' => '291','province_id' => '20','name' => 'بيجار'),
  array('id' => '292','province_id' => '20','name' => 'سقز'),
  array('id' => '293','province_id' => '20','name' => 'كامياران'),
  array('id' => '294','province_id' => '20','name' => 'قروه'),
  array('id' => '295','province_id' => '20','name' => 'مريوان'),
  array('id' => '296','province_id' => '20','name' => 'صلوات آباد'),
  array('id' => '297','province_id' => '20','name' => 'حسن آباد'),
  array('id' => '298','province_id' => '21','name' => 'كرمان'),
  array('id' => '299','province_id' => '21','name' => 'راور'),
  array('id' => '300','province_id' => '21','name' => 'بابك'),
  array('id' => '301','province_id' => '21','name' => 'انار'),
  array('id' => '302','province_id' => '21','name' => 'کوهبنان'),
  array('id' => '303','province_id' => '21','name' => 'رفسنجان'),
  array('id' => '304','province_id' => '21','name' => 'بافت'),
  array('id' => '305','province_id' => '21','name' => 'سيرجان'),
  array('id' => '306','province_id' => '21','name' => 'كهنوج'),
  array('id' => '307','province_id' => '21','name' => 'زرند'),
  array('id' => '308','province_id' => '21','name' => 'بم'),
  array('id' => '309','province_id' => '21','name' => 'جيرفت'),
  array('id' => '310','province_id' => '21','name' => 'بردسير'),
  array('id' => '311','province_id' => '22','name' => 'كرمانشاه'),
  array('id' => '312','province_id' => '22','name' => 'اسلام آباد غرب'),
  array('id' => '313','province_id' => '22','name' => 'سر پل ذهاب'),
  array('id' => '314','province_id' => '22','name' => 'كنگاور'),
  array('id' => '315','province_id' => '22','name' => 'سنقر'),
  array('id' => '316','province_id' => '22','name' => 'قصر شيرين'),
  array('id' => '317','province_id' => '22','name' => 'گيلان غرب'),
  array('id' => '318','province_id' => '22','name' => 'هرسين'),
  array('id' => '319','province_id' => '22','name' => 'صحنه'),
  array('id' => '320','province_id' => '22','name' => 'پاوه'),
  array('id' => '321','province_id' => '22','name' => 'جوانرود'),
  array('id' => '322','province_id' => '22','name' => 'شاهو'),
  array('id' => '323','province_id' => '23','name' => 'ياسوج'),
  array('id' => '324','province_id' => '23','name' => 'گچساران'),
  array('id' => '325','province_id' => '23','name' => 'دنا'),
  array('id' => '326','province_id' => '23','name' => 'دوگنبدان'),
  array('id' => '327','province_id' => '23','name' => 'سي سخت'),
  array('id' => '328','province_id' => '23','name' => 'دهدشت'),
  array('id' => '329','province_id' => '23','name' => 'ليكك'),
  array('id' => '330','province_id' => '24','name' => 'گرگان'),
  array('id' => '331','province_id' => '24','name' => 'آق قلا'),
  array('id' => '332','province_id' => '24','name' => 'گنبد كاووس'),
  array('id' => '333','province_id' => '24','name' => 'علي آباد كتول'),
  array('id' => '334','province_id' => '24','name' => 'مينو دشت'),
  array('id' => '335','province_id' => '24','name' => 'تركمن'),
  array('id' => '336','province_id' => '24','name' => 'كردكوي'),
  array('id' => '337','province_id' => '24','name' => 'بندر گز'),
  array('id' => '338','province_id' => '24','name' => 'كلاله'),
  array('id' => '339','province_id' => '24','name' => 'آزاد شهر'),
  array('id' => '340','province_id' => '24','name' => 'راميان'),
  array('id' => '341','province_id' => '25','name' => 'رشت'),
  array('id' => '342','province_id' => '25','name' => 'منجيل'),
  array('id' => '343','province_id' => '25','name' => 'لنگرود'),
  array('id' => '344','province_id' => '25','name' => 'رود سر'),
  array('id' => '345','province_id' => '25','name' => 'تالش'),
  array('id' => '346','province_id' => '25','name' => 'آستارا'),
  array('id' => '347','province_id' => '25','name' => 'ماسوله'),
  array('id' => '348','province_id' => '25','name' => 'آستانه اشرفيه'),
  array('id' => '349','province_id' => '25','name' => 'رودبار'),
  array('id' => '350','province_id' => '25','name' => 'فومن'),
  array('id' => '351','province_id' => '25','name' => 'صومعه سرا'),
  array('id' => '352','province_id' => '25','name' => 'بندرانزلي'),
  array('id' => '353','province_id' => '25','name' => 'كلاچاي'),
  array('id' => '354','province_id' => '25','name' => 'هشتپر'),
  array('id' => '355','province_id' => '25','name' => 'رضوان شهر'),
  array('id' => '356','province_id' => '25','name' => 'ماسال'),
  array('id' => '357','province_id' => '25','name' => 'شفت'),
  array('id' => '358','province_id' => '25','name' => 'سياهكل'),
  array('id' => '359','province_id' => '25','name' => 'املش'),
  array('id' => '360','province_id' => '25','name' => 'لاهیجان'),
  array('id' => '361','province_id' => '25','name' => 'خشک بيجار'),
  array('id' => '362','province_id' => '25','name' => 'خمام'),
  array('id' => '363','province_id' => '25','name' => 'لشت نشا'),
  array('id' => '364','province_id' => '25','name' => 'بندر کياشهر'),
  array('id' => '365','province_id' => '26','name' => 'خرم آباد'),
  array('id' => '366','province_id' => '26','name' => 'ماهشهر'),
  array('id' => '367','province_id' => '26','name' => 'دزفول'),
  array('id' => '368','province_id' => '26','name' => 'بروجرد'),
  array('id' => '369','province_id' => '26','name' => 'دورود'),
  array('id' => '370','province_id' => '26','name' => 'اليگودرز'),
  array('id' => '371','province_id' => '26','name' => 'ازنا'),
  array('id' => '372','province_id' => '26','name' => 'نور آباد'),
  array('id' => '373','province_id' => '26','name' => 'كوهدشت'),
  array('id' => '374','province_id' => '26','name' => 'الشتر'),
  array('id' => '375','province_id' => '26','name' => 'پلدختر'),
  array('id' => '376','province_id' => '27','name' => 'ساري'),
  array('id' => '377','province_id' => '27','name' => 'آمل'),
  array('id' => '378','province_id' => '27','name' => 'بابل'),
  array('id' => '379','province_id' => '27','name' => 'بابلسر'),
  array('id' => '380','province_id' => '27','name' => 'بهشهر'),
  array('id' => '381','province_id' => '27','name' => 'تنكابن'),
  array('id' => '382','province_id' => '27','name' => 'جويبار'),
  array('id' => '383','province_id' => '27','name' => 'چالوس'),
  array('id' => '384','province_id' => '27','name' => 'رامسر'),
  array('id' => '385','province_id' => '27','name' => 'سواد كوه'),
  array('id' => '386','province_id' => '27','name' => 'قائم شهر'),
  array('id' => '387','province_id' => '27','name' => 'نكا'),
  array('id' => '388','province_id' => '27','name' => 'نور'),
  array('id' => '389','province_id' => '27','name' => 'بلده'),
  array('id' => '390','province_id' => '27','name' => 'نوشهر'),
  array('id' => '391','province_id' => '27','name' => 'پل سفيد'),
  array('id' => '392','province_id' => '27','name' => 'محمود آباد'),
  array('id' => '393','province_id' => '27','name' => 'فريدون كنار'),
  array('id' => '394','province_id' => '28','name' => 'اراك'),
  array('id' => '395','province_id' => '28','name' => 'آشتيان'),
  array('id' => '396','province_id' => '28','name' => 'تفرش'),
  array('id' => '397','province_id' => '28','name' => 'خمين'),
  array('id' => '398','province_id' => '28','name' => 'دليجان'),
  array('id' => '399','province_id' => '28','name' => 'ساوه'),
  array('id' => '400','province_id' => '28','name' => 'سربند'),
  array('id' => '401','province_id' => '28','name' => 'محلات'),
  array('id' => '402','province_id' => '28','name' => 'شازند'),
  array('id' => '403','province_id' => '29','name' => 'بندرعباس'),
  array('id' => '404','province_id' => '29','name' => 'قشم'),
  array('id' => '405','province_id' => '29','name' => 'كيش'),
  array('id' => '406','province_id' => '29','name' => 'بندر لنگه'),
  array('id' => '407','province_id' => '29','name' => 'بستك'),
  array('id' => '408','province_id' => '29','name' => 'حاجي آباد'),
  array('id' => '409','province_id' => '29','name' => 'دهبارز'),
  array('id' => '410','province_id' => '29','name' => 'انگهران'),
  array('id' => '411','province_id' => '29','name' => 'ميناب'),
  array('id' => '412','province_id' => '29','name' => 'ابوموسي'),
  array('id' => '413','province_id' => '29','name' => 'بندر جاسك'),
  array('id' => '414','province_id' => '29','name' => 'تنب بزرگ'),
  array('id' => '415','province_id' => '29','name' => 'بندر خمیر'),
  array('id' => '416','province_id' => '29','name' => 'پارسیان'),
  array('id' => '417','province_id' => '29','name' => 'قشم'),
  array('id' => '418','province_id' => '30','name' => 'همدان'),
  array('id' => '419','province_id' => '30','name' => 'ملاير'),
  array('id' => '420','province_id' => '30','name' => 'تويسركان'),
  array('id' => '421','province_id' => '30','name' => 'نهاوند'),
  array('id' => '422','province_id' => '30','name' => 'كبودر اهنگ'),
  array('id' => '423','province_id' => '30','name' => 'رزن'),
  array('id' => '424','province_id' => '30','name' => 'اسدآباد'),
  array('id' => '425','province_id' => '30','name' => 'بهار'),
  array('id' => '426','province_id' => '31','name' => 'يزد'),
  array('id' => '427','province_id' => '31','name' => 'تفت'),
  array('id' => '428','province_id' => '31','name' => 'اردكان'),
  array('id' => '429','province_id' => '31','name' => 'ابركوه'),
  array('id' => '430','province_id' => '31','name' => 'ميبد'),
  array('id' => '431','province_id' => '31','name' => 'طبس'),
  array('id' => '432','province_id' => '31','name' => 'بافق'),
  array('id' => '433','province_id' => '31','name' => 'مهريز'),
  array('id' => '434','province_id' => '31','name' => 'اشكذر'),
  array('id' => '435','province_id' => '31','name' => 'هرات'),
  array('id' => '436','province_id' => '31','name' => 'خضرآباد'),
  array('id' => '437','province_id' => '31','name' => 'شاهديه'),
  array('id' => '438','province_id' => '31','name' => 'حمیدیه شهر'),
  array('id' => '439','province_id' => '31','name' => 'سید میرزا'),
  array('id' => '440','province_id' => '31','name' => 'زارچ')
);

         DB::table('cities')->insert($city);
    }
}
